services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
        POSTGRES_DB: ${PG_DB}
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data 
    healthcheck: # Ensure DB is ready before the app tries to connect
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s
  app:
    build:
        context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app 
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PORT: ${PG_PORT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
