// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package query_repo

import (
	"context"

	"github.com/google/uuid"
)

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT id, name, email, password_hash, salt, is_admin, created_at, updated_at FROM users
`

func (q *Queries) GetAllPlayers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Salt,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one

INSERT INTO users (
  id,
  name,
  email,
  password_hash,
  salt
) VALUES ( 
    $1, $2, $3, $4, $5
)
RETURNING id, name, email, password_hash, salt, is_admin, created_at, updated_at
`

type InsertUserParams struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Salt         string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
